---
# tasks file for ansible-zookeeper

- name: Launch zookeeper
  docker:
    image: xpatterns/zookeeper:{{ zookeeper_version }}
    name: zookeeper
    command: /usr/bin/run.sh
    hostname: "zookeeper"
    ports:
      - "2181:2181"
    volumes:
      - "{{ data_dir }}/zookeeper:/var/lib/zookeeper/"
    restart_policy: always
    state: started
