---
# tasks file for ansible-zookeeper

- name: Get PWD
  local_action: shell pwd
  register: pwd

- name: Launch zookeeper
  docker:
    image: xpatterns/zookeeper:{{ zookeeper_version }}
    name: zookeeper
    command: /usr/bin/run.sh {{ docker_command }}
    hostname: "zookeeper"
    ports:
      - "5181:5181"
    volumes:
      - "{{ pwd.stdout }}/zookeeper:/var/lib/zookeeper/"
    restart_policy: always
    state: started
